# Generated by Django 4.2.2 on 2023-07-27 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_test_data'),
        ('community', '0001_initial'),
        ('stockAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='analysis_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stockAnalysis.analyzedstocks'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, to='users.profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to='users.profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='publisher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='published_comments', to='users.profile'),
        ),
    ]
