# Generated by Django 4.2.2 on 2023-08-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='NO DESCRIPTION'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='<django.db.models.fields.BigAutoField>', max_length=50),
        ),
    ]
