# Generated by Django 4.2 on 2023-06-28 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_rename_review_comment_alter_post_analysis_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='time',
        ),
    ]
